const Routes = {
  APP_INTRO: 'APP_INTRO',
  AUTH_STACK: 'AUTH_STACK',
  FEEDBACK: 'FEEDBACK',
  HOME_SCREEN: 'HOME',
  LOADING: 'LOADING',
  LOCATION_TRACKING_SCREEN: 'LOCATION_TRACKING_SCREEN',
  LOGIN_SCREEN: 'LOGIN',
  MAIN_STACK: 'Main App',
  MESSAGING_SCREEN: 'MESSAGING_SCREEN',
  ORDER_DETAILS_SCREEN: 'ORDER_DETAILS_SCREEN',
  ORDER_LIST: 'ORDER_LIST',
  ORDER_LIST_CAROUSEL: 'ORDER_LIST_CAROUSEL',
  PROFILE: 'PROFILE',
  PROFILE_EDIT: 'PROFILE_EDIT',
  SETTINGS: 'SETTINGS',
  VIDEO_LIST: 'VIDEO_LIST',
  CHECK_LIST: 'CHECK_LIST',
  SEARCH: 'SEARCH',
  SETTING_SCREEN: 'SETTING_SCREEN',
  SIGN_UP_SCREEN: 'SIGN_UP_SCREEN',
  STORE_MAP_SCREEN: 'STORE_MAP_SCREEN',
  VIDEO_PLAYER_SCREEN: 'VIDEO_PLAYER_SCREEN'
}

export default Routes
